# Generated by Django 4.0.2 on 2022-02-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0016_alter_transactions_date_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pessanger_detail',
            new_name='passenger_detail',
        ),
    ]
